
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 49
#define YY_END_OF_BUFFER 50
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[285] =
    {   0,
        0,    0,    0,    0,    2,    2,    0,    0,    0,    0,
       50,   49,    5,    6,   48,   49,    6,   49,    5,    1,
       49,   49,    2,    2,    2,   49,   49,    5,   49,    7,
       49,   42,   49,    4,   49,   49,   49,   49,   47,    5,
        6,   47,    0,    0,    5,    0,   48,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   19,    0,    0,
        0,    0,    5,    0,    0,    2,    0,    2,    2,    0,
        0,    0,    5,    0,    0,    0,    0,   42,   43,    0,
        0,    0,    0,    0,   47,   47,    5,   48,    0,    5,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   35,   34,    0,    0,    0,
       18,    0,    0,    0,    0,    0,    0,    0,    0,    2,
        0,   46,    0,    5,   46,   46,   46,   46,   46,   44,
       42,   43,   46,   46,   46,   48,    0,    5,    0,    0,
        0,   39,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   33,    0,    0,   21,    0,    0,
        0,   30,    0,    0,    0,    0,    0,    0,    0,    2,
        3,   46,    0,    5,   46,   46,   46,   46,   46,   46,
       44,   44,   46,   42,   43,   46,   46,   46,   48,    0,
        5,    0,    0,    0,    0,    0,   11,    0,   23,    0,

        0,   12,    0,   36,   13,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   22,    0,    0,    2,   46,   46,
       44,   44,   46,   46,   46,   48,    0,    5,    0,   10,
        0,    0,    0,    0,    0,    0,    0,    0,   38,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   45,   44,
       46,    0,    0,   24,   17,   31,   32,   15,    0,    0,
        0,   14,   25,    0,    0,   37,    8,   40,   41,   45,
       46,    0,    0,   29,   26,   28,    9,   20,   45,   46,
       27,   16,   44,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    4,    1,    1,    5,
        6,    1,    4,    7,    8,    9,   10,   11,   12,   12,
       12,   12,   12,   11,   11,   11,   11,   13,    1,    1,
       14,    1,   14,   15,   16,   16,   17,   17,   17,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
        1,   18,    1,    1,   19,    1,   20,   21,   22,   23,

       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   29,   36,   37,   38,   39,   29,   29,   40,
       41,   29,   42,    1,   42,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[43] =
    {   0,
        1,    1,    2,    1,    3,    4,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5
    } ;

static yyconst flex_int16_t yy_base[319] =
    {   0,
        0,   41,   82,  123,    7,   14,  165,    0,   21,   32,
      693,  674,   12,   46,   55,  203,  976,  976,   19,  976,
      663,  670,  671,   52,  670,   47,  668,   64,  245,  976,
      263,  281,  299,  318,   71,  647,  646,  639,  654,   77,
      652,   22,  645,   85,   91,  634,   92,   99,   19,   88,
      630,  621,  609,   98,  620,  110,  619,  976,   62,   63,
       91,  600,   66,  609,  605,  607,   97,  137,  119,  591,
      600,  209,  144,  337,  355,  374,  392,  410,  138,  140,
      599,  200,  206,  142,  594,   27,  250,  336,  411,  428,
      574,  571,  573,  569,  561,  568,  552,  563,  564,  562,

       77,  136,  540,  543,  550,  540,  976,  546,   98,  548,
      976,  542,  192,  543,  525,  535,  519,  531,  521,   39,
      530,  534,  431,  268,  473,  491,  510,  529,  547,  565,
      583,  146,  276,  245,  286,  434,  437,  454,  512,  511,
      513,  976,  504,  509,  516,  496,  509,  501,  498,  484,
      490,  486,  480,  493,  976,  488,  472,  976,  468,  483,
      461,  976,  478,  473,  457,  465,  453,  454,  461,   13,
      976,  464,  460,  342,  601,  471,    0,  619,  208,  353,
        0,  638,  368,    0,  238,  219,  312,  250,  463,  653,
      659,  444,  435,  426,  439,  436,  976,  422,  976,  430,

      429,  976,  422,  976,  976,  420,  427,  417,  400,  392,
      387,  379,  378,  377,  976,  384,  383,  382,  695,  714,
      733,  595,  343,  293,  360,  662,  669,  676,  371,  976,
      358,  366,  356,  365,  350,  357,  345,  322,  976,  308,
      301,  310,  284,  251,  255,  235,  217,  205,  752,  771,
      790,  200,  191,  976,  976,  976,  976,  976,  129,  125,
      111,  976,  976,  108,   99,  976,  976,  976,  976,  808,
      827,   84,   47,  976,  976,  976,  976,  976,    0,  845,
      976,  976,  863,  976,  881,  886,  891,  896,  901,  903,
      907,  912,  914,  916,  918,  920,  925,  927,  929,  931,

      933,  935,  937,  941,  943,  945,  947,  949,  951,  955,
      957,  959,  963,  965,  967,  969,  971,  973
    } ;

static yyconst flex_int16_t yy_def[319] =
    {   0,
      285,  285,  286,  286,  287,  287,  284,    7,  288,  288,
      284,  289,  289,  290,  290,  284,  284,  284,  284,  284,
      284,  284,  291,  291,  291,  291,  292,  292,  293,  284,
      294,  294,  295,  295,  284,   34,   34,   34,  296,  296,
      296,  296,  297,  284,  297,  289,  290,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  291,  291,  291,  291,  291,
      298,  284,  298,  299,  300,  301,  302,  301,   78,   78,
      292,   78,   78,   78,  296,  296,  296,  303,  284,  303,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  291,  291,
      291,  304,  284,  304,  305,  306,  306,  307,  308,  308,
      307,  131,  131,  131,  131,  309,  284,  309,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  291,  291,
      284,  304,  284,  304,  305,  127,  127,  310,  131,  130,
      130,  311,  304,  131,  131,  304,  131,  131,  312,  284,
      312,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  291,  313,  314,
      311,  304,  304,  131,  131,  312,  284,  312,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  315,  314,
      316,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  317,
      316,  284,  284,  284,  284,  284,  284,  284,  127,  318,
      284,  284,  318,    0,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284
    } ;

static yyconst flex_int16_t yy_nxt[1019] =
    {   0,
      284,   13,   13,  284,   14,   14,   15,  284,   24,   24,
      284,   25,   25,   45,   45,   24,   24,   16,   25,   25,
       63,   63,   40,   19,   26,   41,   17,   85,  284,   44,
       67,   26,   85,   40,   19,  218,   41,   17,   42,   86,
       91,   17,   13,   13,   86,   14,   14,   15,   25,   42,
       47,   47,   47,   68,   68,   25,   67,   92,   16,   47,
       47,   47,   41,   48,   69,   73,   73,   63,   63,   67,
       70,  170,   48,   41,  111,   81,   81,   81,   87,   63,
      282,   72,   17,   19,   19,  109,   17,   20,   81,   43,
       43,   43,   90,   90,   86,  110,   47,   47,   47,  149,

      112,  113,   43,   46,   46,   46,   21,   93,   89,   48,
      114,   94,   81,  150,   69,   95,   46,  281,  115,   22,
      119,   96,  158,   17,   19,   19,   43,   17,   20,  100,
      101,  104,  278,  105,  159,  102,   67,  106,   68,   68,
       46,  277,  120,  107,  276,  124,  124,   21,  132,  132,
      132,  132,  132,  132,   67,  151,  185,  185,  275,  152,
       22,  123,  274,  135,   17,   27,   28,   28,   29,   17,
       20,   30,   31,   29,   27,   32,   32,   27,   27,   27,
       33,   34,   35,   31,   33,   33,   34,   34,   34,   36,
       33,   37,   33,   33,   33,   33,   33,   33,   33,   33,

       33,   38,   33,   33,   33,   33,   17,   46,   46,   46,
      132,  132,  162,   71,   71,   71,  132,  132,  179,  179,
       46,  273,   49,  163,   50,   51,   71,   52,  223,   53,
       54,  272,   55,   56,  133,   57,  173,   58,   59,   60,
       61,  269,   62,  134,   46,   71,   71,   71,  185,  185,
       71,   87,   63,  268,   71,  179,  179,   71,   71,   75,
      179,  179,   72,   71,   71,   71,   74,   86,  267,  174,
      174,   77,   71,  225,  266,   71,   71,   75,  265,  187,
       72,   71,   71,   71,   74,  173,  179,  179,  186,   77,
       71,   78,   78,   71,   71,   75,  179,  179,   72,   71,

       71,   71,   74,  179,  179,  186,   76,   77,   71,   79,
       79,   71,   71,   75,  264,  188,   72,   76,   71,   71,
       71,   74,  179,  179,  186,   76,   77,   71,   79,   79,
       71,   71,   75,  263,  262,   72,   76,  122,  122,  122,
       47,   47,   47,  174,  174,  261,  122,  260,  224,  122,
      122,  126,  251,  137,  123,  122,  122,  122,  122,  173,
      173,  175,  172,  122,  122,  172,  259,  122,  122,  122,
      179,  179,  123,  122,  122,  122,  122,  125,  222,  222,
      258,  257,  129,  122,  256,  173,  122,  122,  126,  255,
      254,  123,  122,  122,  122,  125,  253,  224,  252,   67,

      125,  122,  248,  247,  122,  122,  126,  246,  245,  123,
      122,  122,  122,  125,  244,   88,   88,   88,  129,  122,
      131,  131,  122,  122,  126,  243,  242,  123,   88,  138,
      138,  241,   47,   47,   47,  122,  122,  122,   47,   47,
       47,  136,  136,  136,  240,  137,  239,  238,  122,  237,
      236,  190,   88,  235,  136,  191,  191,  234,   47,   47,
       47,  233,  232,  231,  172,  172,  172,   47,   47,   47,
      230,  190,  122,  172,  172,  172,  229,  172,  136,  172,
      227,  173,  172,  284,  217,  172,  172,  176,  216,  215,
      173,  172,  172,  172,  172,  214,  213,  212,  211,  172,

      172,  172,  210,  172,  172,  172,  209,  208,  173,  172,
      172,  172,  172,  172,  207,  206,  205,  204,  178,  172,
      203,  202,  172,  172,  172,  201,  200,  173,  172,  172,
      172,  172,  175,  199,  198,  197,  196,  180,  172,  195,
      194,  172,  172,  176,  193,  192,  173,  172,  172,  172,
      175,  173,  171,  169,  168,  175,  172,  167,  166,  172,
      172,  176,  165,  164,  173,  172,  172,  172,  175,  161,
      160,  157,  156,  180,  182,  155,  154,  183,  172,  176,
      153,  148,  173,  172,  172,  172,  175,  147,  146,  145,
      144,  180,  172,  184,  184,  172,  172,  176,  143,  142,

      173,  172,  172,  172,  182,  222,  222,  141,  140,  139,
      172,   86,  173,  172,  172,  176,   72,  123,  173,  172,
      172,  172,  172,  121,   67,  118,  177,  172,  172,  177,
      177,  172,  172,  172,  117,  116,  173,  172,  172,  172,
      172,  172,  108,  103,   99,  172,  220,  182,   98,   97,
      172,   44,  172,  172,  172,  173,  172,  189,  189,  189,
      228,  228,   89,   47,   47,   47,   47,   47,   47,   86,
      189,   86,   84,  226,  226,  226,  227,  228,  228,  227,
       47,   47,   47,   83,   82,   72,  226,   67,   67,   65,
       64,   44,  284,  227,  189,  172,  172,  172,  172,  284,

      284,  284,  177,  178,  172,  177,  177,  172,  172,  172,
      226,  284,  173,  172,  172,  172,  172,  172,  284,  284,
      284,  172,  172,  172,  284,  284,  172,  172,  172,  172,
      172,  173,  172,  172,  172,  172,  172,  284,  284,  284,
      172,  220,  182,  284,  284,  172,  284,  172,  172,  172,
      173,  172,  172,  172,  172,  172,  284,  284,  284,  177,
      178,  172,  177,  177,  172,  172,  172,  284,  284,  173,
      172,  172,  172,  172,  172,  284,  284,  284,  172,  172,
      182,  284,  284,  172,  172,  172,  172,  172,  173,  172,
      172,  172,  172,  172,  284,  284,  284,  284,  172,  172,

      284,  284,  172,  172,  172,  284,  284,  173,  172,  172,
      172,  172,  284,  284,  284,  177,  178,  172,  177,  177,
      172,  172,  172,  284,  284,  173,  172,  172,  172,  172,
      172,  284,  284,  284,  284,  280,  172,  284,  284,  172,
      172,  172,  284,  284,  173,  172,  172,  172,  172,  284,
      284,  284,  284,  172,  172,  284,  284,  172,  172,  172,
      284,  284,  173,  172,  172,  172,  172,  284,  284,  284,
      284,  280,  182,  284,  284,  183,  172,  172,  284,  284,
      173,   12,   12,   12,   12,   12,   18,   18,   18,   18,
       18,   23,   23,   23,   23,   23,   39,   39,   39,   39,

       39,   43,   43,   46,   46,   46,   46,   66,   66,   66,
       66,   66,   71,   71,   74,   74,   76,   76,   80,   80,
       85,  284,   85,  284,   85,   88,   88,  122,  122,  125,
      125,  127,  127,  128,  128,  130,  130,  136,  136,  136,
      136,  172,  172,  175,  175,  177,  177,  179,  179,  181,
      181,  189,  189,  189,  189,  219,  219,  221,  221,  226,
      226,  226,  226,  249,  249,  250,  250,  270,  270,  271,
      271,  279,  279,  283,  283,   11,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284
    } ;

static yyconst flex_int16_t yy_chk[1019] =
    {   0,
        0,    1,    1,    0,    1,    1,    1,    0,    5,    5,
        0,    5,    5,   13,   13,    6,    6,    1,    6,    6,
       19,   19,    9,    9,    5,    9,    9,   42,    0,   13,
      170,    6,   86,   10,   10,  170,   10,   10,    9,   42,
       49,    1,    2,    2,   86,    2,    2,    2,    5,   10,
       14,   14,   14,   24,   24,    6,  120,   49,    2,   15,
       15,   15,    9,   14,   26,   28,   28,   63,   63,   24,
       26,  120,   15,   10,   60,   35,   35,   35,   40,   40,
      273,   28,    2,    3,    3,   59,    3,    3,   35,   44,
       44,   44,   45,   45,   40,   59,   47,   47,   47,  101,

       60,   60,   44,   48,   48,   48,    3,   50,   45,   47,
       61,   50,   35,  101,   67,   50,   48,  272,   61,    3,
       67,   50,  109,    3,    4,    4,   44,    4,    4,   54,
       54,   56,  265,   56,  109,   54,   69,   56,   68,   68,
       48,  264,   69,   56,  261,   73,   73,    4,   79,   79,
       80,   80,   84,   84,   68,  102,  132,  132,  260,  102,
        4,   73,  259,   84,    4,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,   16,   16,   16,
       82,   82,  113,   72,   72,   72,   83,   83,  179,  179,
       16,  253,   16,  113,   16,   16,   72,   16,  186,   16,
       16,  252,   16,   16,   82,   16,  186,   16,   16,   16,
       16,  248,   16,   83,   16,   29,   29,   29,  185,  185,
       72,   87,   87,  247,   29,  134,  134,   29,   29,   29,
      188,  188,   29,   31,   31,   31,   31,   87,  246,  124,
      124,   31,   31,  188,  245,   31,   31,   31,  244,  134,
       31,   32,   32,   32,   32,  124,  133,  133,  133,   32,
       32,   32,   32,   32,   32,   32,  135,  135,   32,   33,

       33,   33,   33,  224,  224,  224,   33,   33,   33,   33,
       33,   33,   33,   33,  243,  135,   33,   33,   34,   34,
       34,   34,  187,  187,  187,   34,   34,   34,   34,   34,
       34,   34,   34,  242,  241,   34,   34,   74,   74,   74,
       88,   88,   88,  174,  174,  240,   74,  238,  187,   74,
       74,   74,  223,   88,   74,   75,   75,   75,   75,  174,
      223,  180,  180,   75,   75,  180,  237,   75,   75,   75,
      225,  225,   75,   75,   76,   76,   76,   76,  183,  183,
      236,  235,   76,   76,  234,  183,   76,   76,   76,  233,
      232,   76,   77,   77,   77,   77,  231,  225,  229,  218,

       77,   77,  217,  216,   77,   77,   77,  214,  213,   77,
       78,   78,   78,   78,  212,   89,   89,   89,   78,   78,
       78,   78,   78,   78,   78,  211,  210,   78,   89,   90,
       90,  209,   90,   90,   90,  123,  123,  123,  136,  136,
      136,  137,  137,  137,  208,   90,  207,  206,  123,  203,
      201,  136,   89,  200,  137,  138,  138,  198,  138,  138,
      138,  196,  195,  194,  173,  173,  173,  189,  189,  189,
      193,  138,  123,  125,  125,  125,  192,  173,  137,  176,
      189,  172,  125,  169,  168,  125,  125,  125,  167,  166,
      125,  126,  126,  126,  126,  165,  164,  163,  161,  126,

      126,  173,  160,  126,  126,  126,  159,  157,  126,  126,
      127,  127,  127,  127,  156,  154,  153,  152,  127,  127,
      151,  150,  127,  127,  127,  149,  148,  127,  127,  128,
      128,  128,  128,  147,  146,  145,  144,  128,  128,  143,
      141,  128,  128,  128,  140,  139,  128,  129,  129,  129,
      129,  122,  121,  119,  118,  129,  129,  117,  116,  129,
      129,  129,  115,  114,  129,  130,  130,  130,  130,  112,
      110,  108,  106,  130,  130,  105,  104,  130,  130,  130,
      103,  100,  130,  131,  131,  131,  131,   99,   98,   97,
       96,  131,  131,  131,  131,  131,  131,  131,   95,   94,

      131,  175,  175,  175,  222,  222,  222,   93,   92,   91,
      175,   85,  222,  175,  175,  175,   81,   71,  175,  178,
      178,  178,  178,   70,   66,   65,  178,  178,  178,  178,
      178,  178,  178,  178,   64,   62,  178,  178,  182,  182,
      182,  182,   57,   55,   53,  182,  182,  182,   52,   51,
      182,   46,  182,  182,  182,  182,  182,  190,  190,  190,
      191,  191,   43,  191,  191,  191,  226,  226,  226,   41,
      190,   39,   38,  227,  227,  227,  191,  228,  228,  226,
      228,  228,  228,   37,   36,   27,  227,   25,   23,   22,
       21,   12,   11,  228,  190,  219,  219,  219,  219,    0,

        0,    0,  219,  219,  219,  219,  219,  219,  219,  219,
      227,    0,  219,  219,  220,  220,  220,  220,    0,    0,
        0,  220,  220,  220,    0,    0,  220,  220,  220,  220,
      220,  220,  220,  221,  221,  221,  221,    0,    0,    0,
      221,  221,  221,    0,    0,  221,    0,  221,  221,  221,
      221,  221,  249,  249,  249,  249,    0,    0,    0,  249,
      249,  249,  249,  249,  249,  249,  249,    0,    0,  249,
      249,  250,  250,  250,  250,    0,    0,    0,  250,  250,
      250,    0,    0,  250,  250,  250,  250,  250,  250,  250,
      251,  251,  251,  251,    0,    0,    0,    0,  251,  251,

        0,    0,  251,  251,  251,    0,    0,  251,  270,  270,
      270,  270,    0,    0,    0,  270,  270,  270,  270,  270,
      270,  270,  270,    0,    0,  270,  270,  271,  271,  271,
      271,    0,    0,    0,    0,  271,  271,    0,    0,  271,
      271,  271,    0,    0,  271,  280,  280,  280,  280,    0,
        0,    0,    0,  280,  280,    0,    0,  280,  280,  280,
        0,    0,  280,  283,  283,  283,  283,    0,    0,    0,
        0,  283,  283,    0,    0,  283,  283,  283,    0,    0,
      283,  285,  285,  285,  285,  285,  286,  286,  286,  286,
      286,  287,  287,  287,  287,  287,  288,  288,  288,  288,

      288,  289,  289,  290,  290,  290,  290,  291,  291,  291,
      291,  291,  292,  292,  293,  293,  294,  294,  295,  295,
      296,    0,  296,    0,  296,  297,  297,  298,  298,  299,
      299,  300,  300,  301,  301,  302,  302,  303,  303,  303,
      303,  304,  304,  305,  305,  306,  306,  307,  307,  308,
      308,  309,  309,  309,  309,  310,  310,  311,  311,  312,
      312,  312,  312,  313,  313,  314,  314,  315,  315,  316,
      316,  317,  317,  318,  318,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "flex.fl"
#line 2 "flex.fl"
#include "y.tab.h"
#include <stdlib.h>



#line 780 "lex.yy.c"

#define INITIAL 0
#define INDICE 1
#define CODIGO 2
#define ARGS 3
#define CODIGOLINHA 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 19 "flex.fl"



#line 970 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 285 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 976 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INDICE):
case YY_STATE_EOF(CODIGO):
case YY_STATE_EOF(ARGS):
case YY_STATE_EOF(CODIGOLINHA):
#line 22 "flex.fl"
{return '$';}
	YY_BREAK
case 1:
YY_RULE_SETUP
#line 23 "flex.fl"
{BEGIN 0; return ')';}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 24 "flex.fl"
{printf("CODIGO:%s",yytext);
					 yylval.valS = strdup(yytext);
					return codigo;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 27 "flex.fl"
{BEGIN 0; return ENDCOD;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 28 "flex.fl"
{printf("CHAR:%s\n",yytext);yylval.valC = yytext[0];
				 	return carater;}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 34 "flex.fl"
{;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 35 "flex.fl"
{printf("PARAM|%s|\n",yytext);return yytext[0];} 
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 36 "flex.fl"
{printf("SEP:%s\n",yytext );return sep;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 38 "flex.fl"
{BEGIN ARGS; return BTITLE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 39 "flex.fl"
{BEGIN ARGS; return BSTITLE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 40 "flex.fl"
{BEGIN ARGS;return BAUTHOR;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 41 "flex.fl"
{BEGIN ARGS;return BDATE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 42 "flex.fl"
{BEGIN ARGS;return BINST;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 43 "flex.fl"
{BEGIN ARGS;return BKEY;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 44 "flex.fl"
{return BABS;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 45 "flex.fl"
{BEGIN INDICE;	
				return BINDICE;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 48 "flex.fl"
{BEGIN ARGS;
				return BCHAP;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 50 "flex.fl"
{BEGIN CODIGO; return BCODE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 51 "flex.fl"
{BEGIN ARGS;
				yylval.valI = yytext[2]-'0';
				return BSEC;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 55 "flex.fl"
{return BPARAG;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 56 "flex.fl"
{return BSUMMARY;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "flex.fl"
{return BREF;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "flex.fl"
{return BXREF;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "flex.fl"
{return BHREF;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "flex.fl"
{return BCiteR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 61 "flex.fl"
{return BFoteN;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 62 "flex.fl"
{return BLineCode;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "flex.fl"
{return BAcronym;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 65 "flex.fl"
{return BBOLD;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 66 "flex.fl"
{return BITALIC;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 67 "flex.fl"
{return BUNDERLINE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "flex.fl"
{return BFIG;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "flex.fl"
{return BImg;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "flex.fl"
{BEGIN ARGS;
				return BCAP;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "flex.fl"
{return BENUM;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "flex.fl"
{return BITEMIZE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "flex.fl"
{return BITEM;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 78 "flex.fl"
{return BTAB;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 79 "flex.fl"
{return BLINHA;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 80 "flex.fl"
{BEGIN ARGS;
				return BCEL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 84 "flex.fl"
{return IFIGURE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 85 "flex.fl"
{return ITABLE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 91 "flex.fl"
{printf("INTEIRO:%s\n",yytext);yylval.valI = atoi(strdup(yytext));
				return inteiro;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 94 "flex.fl"
{printf("ID:%s\n",yytext);yylval.valS = strdup(yytext);
					return id;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 96 "flex.fl"
{printf("URL%s\n",yytext );
					yylval.valS = strdup(yytext);
					return url;}			
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 99 "flex.fl"
{printf("EMAIL:%s\n",yytext);
					yylval.valS = strdup(yytext);
					return email;}
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 102 "flex.fl"
{printf("ARGS:%s\n",yytext); yylval.valS = strdup(yytext);
					return arg;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 104 "flex.fl"
{printf("LINHA:%s\n",yytext);yylval.valS = strdup(yytext);
					 return linha;}			
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 106 "flex.fl"
{printf("TEXTO:%s\n",yytext);yylval.valS = strdup(yytext);
					return texto;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "flex.fl"
ECHO;
	YY_BREAK
#line 1328 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 285 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 285 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 284);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 111 "flex.fl"



int yywrap() {}
